### PR TITLE
clone tasmota flasher, change partitions, rename, update tool

### PR DESCRIPTION
**Pull request by MichaelDvP**
Build of windows/ubuntu and macOS is gh-action, but not automatically relaesed. Partitions are taken online from the partitions folder.

### CODE REVIEW

**Comment by proddy** [comment]
yippy!

**Comment by MichaelDvP** [comment]
The binaries are stored under Artifacts on this page: https://github.com/emsesp/EMS-ESP-Flasher/actions/runs/3364151868
You eed to copy them to a new release, otherwise people don't find them.

**Comment by proddy** [comment]
> You eed to copy them to a new release, otherwise people don't find them.

why can't you do this?

**Comment by MichaelDvP** [comment]
Here i have no access. I tried automatic release, but get unspecified errors and dont want to spend hours to figure out what is wrong for copying 3 files.

**Comment by proddy** [comment]
ok, strange. You should have full rights to the EMS-ESP organization. I'll check & fix

EDIT: think I fixed it now, renamed the dev team to owners and granted access to this new repo

**Comment by proddy** [comment]
done. https://github.com/emsesp/EMS-ESP-Flasher/releases/tag/v1.0.0

**Pull request merged**
